Prepare for 1.4.2
microsoft/vscode-react-native pull request #1541
Opened 2021-04-06 15:11 UTC by JiglioNero

2021-04-06 15:28 UTC, etatanova requested changes

2021-04-06 15:28 UTC, etatanova commented on CHANGELOG.md
> +    * Improve sending error events to Telemetry [#1526](https://github.com/microsoft/vscode-react-native/pull/1526)
```suggestion
    * Improved sending error events to Telemetry [#1526](https://github.com/microsoft/vscode-react-native/pull/1526)
```

2021-04-06 15:28 UTC, etatanova commented on CHANGELOG.md
> +* Added debugging support for AppleTV [#1498](https://github.com/microsoft/vscode-react-native/pull/1498)
```suggestion
* Added support for debugging AppleTV apps [#1498](https://github.com/microsoft/vscode-react-native/pull/1498)
```

2021-04-06 15:28 UTC, etatanova commented on CHANGELOG.md
> +* Resolved confict with [vscode-jest](https://github.com/jest-community/vscode-jest) extension while fast refreshing React Native apps [#1530](https://github.com/microsoft/vscode-react-native/pull/15
```suggestion
* Resolved a conflict with [vscode-jest](https://github.com/jest-community/vscode-jest) extension while fast refreshing React Native apps [#1530](https://github.com/microsoft/vscode-react-native/pull/1530)
```

2021-04-07 07:49 UTC, etatanova approved these changes

2021-04-09 07:25 UTC, RedMickey commented on CHANGELOG.md
> +* Added support for debugging AppleTV apps [#1498](https://github.com/microsoft/vscode-react-native/pull/1498)
```suggestion
* Added support for debugging AppleTV apps, thanks to [Michele Bonazza(@micheleb)](https://github.com/micheleb) [#1498](https://github.com/microsoft/vscode-react-native/pull/1498)
```

2021-04-26 13:23 UTC, etatanova commented on CHANGELOG.md
> +* Improved extension security [#1538](https://github.com/microsoft/vscode-react-native/pull/1538), [#1527](https://github.com/microsoft/vscode-react-native/pull/1527), [1547](https://github.com/micro
```suggestion
* Improved extension security [#1538](https://github.com/microsoft/vscode-react-native/pull/1538), [#1527](https://github.com/microsoft/vscode-react-native/pull/1527), [#1547](https://github.com/microsoft/vscode-react-native/pull/1547)
```

2021-04-26 13:25 UTC, etatanova approved these changes

2021-04-27 06:53 UTC, merged